### PR TITLE
Use key mappings array to consolidate handler registration logic

### PR DESCRIPTION
**Pull request by theRealPadster**
Is simpler.

### CODE REVIEW

**Comment by KeeMeng** [comment]
Nice! Have you tried if it works? My spicetify doesn’t want to load.

**Comment by theRealPadster** [comment]
I haven't actually ran it in Spicetify, but I ran the JS to output the key and percentage loop values and they come through fine. The code is equivalent. 

JSBin example: https://jsbin.com/qibopogati/1/edit?js,console

**Comment by KeeMeng** [comment]
I’m a bit worried as I tried a used a for loop before, but it did not work

**Comment by KeeMeng** [comment]
Thanks for your contribution! I had to change some stuff too so I closed this pr.

**Comment by theRealPadster** [comment]
Nice, it works?

**Comment by KeeMeng** [comment]
Yup, managed to fix spicetify finally

**Pull request closed without merging**
